ALTER TABLE "venues" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "city" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "country" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "address" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "city" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "country" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "postal_code" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "state" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "latitude" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "longitude" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "logo" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "banner" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "link" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "static_map_url" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_id" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_name" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_maps_link" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_locality" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_area_level_1" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_postal_code" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_country" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_country_code" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_phone_number" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_website_url" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_avg_rating" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "google_total_reviews" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "timezone_id" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "timezone_name" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "utc_offset" numeric;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "dts_offset" numeric;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "currency_code" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "wheelchair_accessible" boolean;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "venue_type" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "ai_description" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "instagram" text;--> statement-breakpoint
CREATE INDEX "idx_venues_name" ON "venues" USING btree ("name");