CREATE TABLE "legacy_venues" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"address" text NOT NULL,
	"city" uuid,
	"logo" text,
	"latitude" text,
	"longitude" text,
	"banner" text,
	"link" text,
	"static_map_url" text,
	"google_name" text,
	"google_street_number" text,
	"google_neighborhood" text,
	"google_route" text,
	"google_sublocality" text,
	"google_locality" text,
	"google_area_level_1" text,
	"google_area_level_2" text,
	"google_postal_code" text,
	"google_country" text,
	"google_country_code" text,
	"google_id" text,
	"google_maps_link" text,
	"timezone_id" text,
	"timezone_name" text,
	"utc_offset" numeric,
	"dts_offset" numeric,
	"google_total_reviews" text,
	"google_avg_rating" text,
	"google_website_url" text,
	"google_phone_number" text,
	"currency_code" text,
	"wheelchair_accessible" boolean,
	"venue_type" text,
	"ai_description" text,
	"instagram" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_legacy_venues_name" ON "legacy_venues" USING btree ("name");