"use client";

import { useState, useMemo } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { SimpleDateTimePicker } from "@/components/ui/simple-datetime-picker";
import { Sparkles, Calendar } from "lucide-react";
import type { EventDayOutput } from "@/actions/event-days";

type EventDay = EventDayOutput;

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onGenerate: (days: Partial<EventDay>[]) => void;
  existingDays: EventDay[];
}

export function AutoGenerateDialog({
  open,
  onOpenChange,
  onGenerate,
  existingDays,
}: AutoGenerateDialogProps) {
  const [startDate, setStartDate] = useState<string>("");
  const [endDate, setEndDate] = useState<string>("");
  const [namingPattern, setNamingPattern] = useState<"numbered" | "weekday">(
    "numbered"
  );
  const [error, setError] = useState<string | null>(null);

  // Calculate preview of days to be generated
  const previewDays = useMemo(() => {
    if (!startDate || !endDate) return [];

    const start = new Date(startDate);
    const end = new Date(endDate);

    if (end <= start) return [];

    const days: Partial<EventDay>[] = [];
    const current = new Date(start);
    let dayNumber = existingDays.length + 1;

    while (current <= end) {
      const name =
        namingPattern === "weekday"
          ? current.toLocaleDateString("es-ES", { weekday: "long" })
          : `Día ${dayNumber}`;

      days.push({
        id: `temp-${current.getTime()}`,
        name: name.charAt(0).toUpperCase() + name.slice(1),
        date: current.toISOString(),
        endDate: "",
        sortOrder: existingDays.length + days.length,
        description: "",
        flyer: "",
        doorsOpen: "",
        showStart: "",
      });

      current.setDate(current.getDate() + 1);
      dayNumber++;
    }

    return days;
  }, [startDate, endDate, namingPattern, existingDays.length]);

  const handleGenerate = () => {
    if (!startDate || !endDate) {
      setError("Por favor selecciona las fechas de inicio y fin");
      return;
    }

    if (new Date(endDate) <= new Date(startDate)) {
      setError("La fecha de fin debe ser posterior a la fecha de inicio");
      return;
    }

    if (previewDays.length === 0) {
      setError("No se generaron días. Verifica las fechas seleccionadas.");
      return;
    }

    if (previewDays.length > 30) {
      setError("No puedes generar más de 30 días a la vez");
      return;
    }

    setError(null);
    onGenerate(previewDays);
    onOpenChange(false);

    // Reset form
    setStartDate("");
    setEndDate("");
    setNamingPattern("numbered");
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className="sm:max-w-[500px] bg-background/95 backdrop-blur-xl border-white/10 [&>div:first-child]:pointer-events-none"
        onPointerDownOutside={(e) => {
          const target = e.target as HTMLElement;
          if (target.closest("[data-date-picker-calendar]")) {
            e.preventDefault();
          }
        }}
        onInteractOutside={(e) => {
          const target = e.target as HTMLElement;
          if (target.closest("[data-date-picker-calendar]")) {
            e.preventDefault();
          }
        }}
      >
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <Sparkles className="w-5 h-5" />
            Auto-Generar Días
          </DialogTitle>
          <DialogDescription>
            Crea múltiples días consecutivos automáticamente entre dos fechas.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Date Range */}
          <div className="space-y-4">
            <h3 className="text-sm font-semibold text-white/70 uppercase tracking-wider flex items-center gap-2">
              <Calendar className="w-4 h-4" />
              Rango de Fechas
            </h3>

            <div className="grid grid-cols-2 gap-4">
              <SimpleDateTimePicker
                name="auto-start-date"
                label="Fecha Inicial"
                value={startDate}
                onChange={(value) => {
                  setStartDate(value);
                  setError(null);
                }}
                placeholder="Inicio"
                required
              />
              <SimpleDateTimePicker
                name="auto-end-date"
                label="Fecha Final"
                value={endDate}
                onChange={(value) => {
                  setEndDate(value);
                  setError(null);
                }}
                placeholder="Fin"
                minDate={startDate ? new Date(startDate) : undefined}
                required
              />
            </div>
          </div>

          {/* Naming Pattern */}
          <div className="space-y-3">
            <Label className="text-sm font-medium">Patrón de Nombres</Label>
            <RadioGroup
              value={namingPattern}
              onValueChange={(value) =>
                setNamingPattern(value as "numbered" | "weekday")
              }
              className="grid grid-cols-2 gap-3"
            >
              <Label
                htmlFor="numbered"
                className={`flex flex-col gap-2 p-3 rounded-xl border-2 transition-all cursor-pointer ${
                  namingPattern === "numbered"
                    ? "border-zinc-400 dark:border-zinc-600 bg-zinc-100 dark:bg-zinc-800"
                    : "border-zinc-200 dark:border-zinc-800 hover:border-zinc-300 dark:hover:border-zinc-700"
                }`}
              >
                <div className="flex items-center gap-2">
                  <RadioGroupItem value="numbered" id="numbered" />
                  <div className="text-sm font-medium">Numerado</div>
                </div>
                <div className="text-xs text-zinc-500 dark:text-zinc-400 ml-6">
                  Día 1, Día 2, Día 3...
                </div>
              </Label>
              <Label
                htmlFor="weekday"
                className={`flex flex-col gap-2 p-3 rounded-xl border-2 transition-all cursor-pointer ${
                  namingPattern === "weekday"
                    ? "border-zinc-400 dark:border-zinc-600 bg-zinc-100 dark:bg-zinc-800"
                    : "border-zinc-200 dark:border-zinc-800 hover:border-zinc-300 dark:hover:border-zinc-700"
                }`}
              >
                <div className="flex items-center gap-2">
                  <RadioGroupItem value="weekday" id="weekday" />
                  <div className="text-sm font-medium">Días de Semana</div>
                </div>
                <div className="text-xs text-zinc-500 dark:text-zinc-400 ml-6">
                  Viernes, Sábado...
                </div>
              </Label>
            </RadioGroup>
          </div>

          {/* Preview */}
          {previewDays.length > 0 && (
            <div className="space-y-3">
              <Label className="text-sm font-medium">
                Vista Previa ({previewDays.length}{" "}
                {previewDays.length === 1 ? "día" : "días"})
              </Label>
              <div className="max-h-48 overflow-y-auto space-y-2 p-3 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/50">
                {previewDays.slice(0, 10).map((day, index) => (
                  <div
                    key={index}
                    className="flex items-center gap-3 text-sm py-1"
                  >
                    <div className="w-6 h-6 rounded-full bg-zinc-200 dark:bg-zinc-700 flex items-center justify-center text-xs font-bold">
                      {existingDays.length + index + 1}
                    </div>
                    <div className="flex-1">
                      <span className="font-medium">{day.name}</span>
                      <span className="text-zinc-500 dark:text-zinc-400 ml-2">
                        •{" "}
                        {new Date(day.date!).toLocaleDateString("es-ES", {
                          month: "short",
                          day: "numeric",
                        })}
                      </span>
                    </div>
                  </div>
                ))}
                {previewDays.length > 10 && (
                  <div className="text-xs text-center text-zinc-500 dark:text-zinc-400 pt-2">
                    ... y {previewDays.length - 10} más
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Error Message */}
          {error && (
            <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/20">
              <p className="text-sm text-red-500 font-medium">{error}</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-3 pt-4 border-t border-white/10">
          <Button
            type="button"
            variant="outline"
            onClick={() => {
              onOpenChange(false);
              setError(null);
            }}
            className="rounded-full px-6"
          >
            Cancelar
          </Button>
          <Button
            type="button"
            onClick={handleGenerate}
            disabled={previewDays.length === 0}
            className="rounded-full px-6 bg-primary hover:bg-primary/90"
          >
            <Sparkles className="w-4 h-4 mr-2" />
            Generar {previewDays.length > 0 && `(${previewDays.length})`}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
